"""Public API for Renderhane's deterministic Relief Pro Phase 0 engine."""

from .mesh_ops import (
    build_rectangular_relief_mesh,
    build_silhouette_relief_mesh,
    count_open_edges,
    trace_boundary_loops,
    validate_mesh,
)
from .models import (
    ENGINE_NAME,
    ENGINE_VERSION,
    FIXED_ZIP_TIME,
    MAX_SOURCE_FILE_BYTES,
    MAX_SOURCE_PIXELS,
    REPORT_SCHEMA_VERSION,
    BuildRecipe,
    BuildReport,
    MeshValidation,
    NormalizationMode,
    ShapeMode,
    canonical_json_bytes,
    dependency_versions,
    inspect_source_image,
    sha256_bytes,
    sha256_file,
)
from .pipeline import build
from .semantic_ops import (
    SEMANTIC_ENGINE_VERSION,
    SEMANTIC_RECIPE_SCHEMA_VERSION,
    SEMANTIC_REPORT_SCHEMA_VERSION,
    SemanticReliefInputError,
    compile_semantic_relief,
)

__all__ = [
    "ENGINE_NAME",
    "ENGINE_VERSION",
    "FIXED_ZIP_TIME",
    "MAX_SOURCE_FILE_BYTES",
    "MAX_SOURCE_PIXELS",
    "REPORT_SCHEMA_VERSION",
    "BuildRecipe",
    "BuildReport",
    "MeshValidation",
    "NormalizationMode",
    "ShapeMode",
    "build",
    "compile_semantic_relief",
    "build_rectangular_relief_mesh",
    "build_silhouette_relief_mesh",
    "canonical_json_bytes",
    "count_open_edges",
    "dependency_versions",
    "inspect_source_image",
    "sha256_bytes",
    "sha256_file",
    "SEMANTIC_ENGINE_VERSION",
    "SEMANTIC_RECIPE_SCHEMA_VERSION",
    "SEMANTIC_REPORT_SCHEMA_VERSION",
    "SemanticReliefInputError",
    "trace_boundary_loops",
    "validate_mesh",
]
