import "server-only";

/**
 * Shopify Admin API client for product image operations.
 *
 * Users connect their Shopify store by providing:
 * - Store URL (e.g. mystore.myshopify.com)
 * - Admin API Access Token (from Custom App in Shopify Admin)
 *
 * Required Shopify scopes: read_products, write_products
 */

interface ShopifyProduct {
  id: number;
  title: string;
  handle: string;
  images: ShopifyImage[];
  image: ShopifyImage | null;
}

interface ShopifyImage {
  id: number;
  product_id: number;
  src: string;
  alt: string | null;
  width: number;
  height: number;
}

interface ShopifyProductsResponse {
  products: ShopifyProduct[];
}

const SHOPIFY_DOMAIN_PATTERN =
  /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.myshopify\.com$/;

export function normalizeShopDomain(shopDomain: string): string {
  const input = shopDomain.trim().toLowerCase();
  const candidate = input.includes("://") ? input : `https://${input}`;
  let url: URL;

  try {
    url = new URL(candidate);
  } catch {
    throw new Error("Invalid Shopify store domain");
  }

  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    url.port ||
    (url.pathname !== "/" && url.pathname !== "") ||
    url.search ||
    url.hash ||
    !SHOPIFY_DOMAIN_PATTERN.test(url.hostname)
  ) {
    throw new Error("Shopify store must use a valid *.myshopify.com domain");
  }

  return url.hostname;
}

export class ShopifyClient {
  private baseUrl: string;
  private headers: Record<string, string>;

  constructor(shopDomain: string, accessToken: string) {
    const domain = normalizeShopDomain(shopDomain);

    this.baseUrl = `https://${domain}/admin/api/2024-01`;
    this.headers = {
      "X-Shopify-Access-Token": accessToken,
      "Content-Type": "application/json",
    };
  }

  /**
   * Verify the connection is valid by fetching shop info.
   */
  async verifyConnection(): Promise<{ name: string; domain: string }> {
    const res = await fetch(`${this.baseUrl}/shop.json`, {
      headers: this.headers,
    });

    if (!res.ok) {
      throw new Error(`Shopify API error: ${res.status}`);
    }

    const data = await res.json();
    return {
      name: data.shop.name,
      domain: data.shop.myshopify_domain,
    };
  }

  /**
   * Fetch products with their images.
   */
  async getProducts(limit = 50, pageInfo?: string): Promise<{
    products: ShopifyProduct[];
    nextPageInfo: string | null;
  }> {
    const safeLimit = Number.isInteger(limit)
      ? Math.min(Math.max(limit, 1), 250)
      : 50;
    const url = new URL(`${this.baseUrl}/products.json`);
    url.searchParams.set("limit", String(safeLimit));
    if (pageInfo) {
      if (pageInfo.length > 4096) {
        throw new Error("Invalid Shopify pagination token");
      }
      url.searchParams.set("page_info", pageInfo);
    } else {
      url.searchParams.set("fields", "id,title,handle,images,image");
    }

    const res = await fetch(url, { headers: this.headers });
    if (!res.ok) {
      throw new Error(`Shopify API error: ${res.status}`);
    }

    const data: ShopifyProductsResponse = await res.json();

    // Parse Link header for pagination
    const linkHeader = res.headers.get("link");
    let nextPageInfo: string | null = null;
    if (linkHeader) {
      const nextMatch = linkHeader.match(/<[^>]*page_info=([^&>]+)[^>]*>;\s*rel="next"/);
      if (nextMatch) nextPageInfo = nextMatch[1];
    }

    return { products: data.products, nextPageInfo };
  }

  /**
   * Upload a new image to a product.
   */
  async addProductImage(
    productId: number,
    imageUrl: string,
    alt?: string
  ): Promise<ShopifyImage> {
    const res = await fetch(
      `${this.baseUrl}/products/${productId}/images.json`,
      {
        method: "POST",
        headers: this.headers,
        body: JSON.stringify({
          image: {
            src: imageUrl,
            alt: alt || "Generated by Renderhane AI",
          },
        }),
      }
    );

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Failed to upload image: ${error}`);
    }

    const data = await res.json();
    return data.image;
  }

  /**
   * Replace a product's main image.
   */
  async updateProductImage(
    productId: number,
    imageId: number,
    newSrc: string
  ): Promise<ShopifyImage> {
    const res = await fetch(
      `${this.baseUrl}/products/${productId}/images/${imageId}.json`,
      {
        method: "PUT",
        headers: this.headers,
        body: JSON.stringify({
          image: { id: imageId, src: newSrc },
        }),
      }
    );

    if (!res.ok) {
      throw new Error(`Failed to update image: ${res.status}`);
    }

    const data = await res.json();
    return data.image;
  }
}
