import type { IdeaChannel } from "./inspiration";

const COPY: Array<[string, string]> = [
  ["ANA SAYFA", "HOME"],
  ["ARAÇLAR", "TOOLS"],
  ["Arka plan kaldır", "Remove background"],
  ["QR kod oluştur", "Create QR code"],
  ["NFC etiket yaz", "Write NFC tag"],
  ["Üretim alanı sade.", "A focused workspace."],
  ["Dosyanız, ayarlarınız ve sonuç aynı yerde.", "Your file, settings, and result stay together."],
  ["Arka planı ", "Leave the background "],
  ["geride bırak.", "behind."],
  ["Ürün fotoğrafını yükle. Sade bir çalışma alanında incele, arka planını düzenle ve çıktını indir.", "Upload a product photo, review it in a focused workspace, adjust the background, and download the result."],
  ["Kayıt olmadan", "No signup"],
  ["Günde 3 ücretsiz kullanım", "3 free uses per day"],
  ["Şeffaf PNG", "Transparent PNG"],
  ["Kendi fotoğrafınla başla", "Start with your own photo"],
  ["Fotoğraf seç", "Choose photo"],
  ["Fotoğraf ve çıktı", "Photo and output"],
  ["API bağlı", "API connected"],
  ["Fotoğrafı değiştir", "Change photo"],
  ["Fotoğrafını buraya bırak", "Drop your photo here"],
  ["veya dosya seç", "or choose a file"],
  ["en fazla 5 MB", "up to 5 MB"],
  ["Ürün fotoğrafı seç", "Choose a product photo"],
  ["Çıktı biçimi", "Output format"],
  ["Boyut", "Size"],
  ["Kaynak boyutu", "Original size"],
  ["Arka plan", "Background"],
  ["PNG önizlemesi", "PNG preview"],
  ["Şeffaf arka plan", "Transparent background"],
  ["İşleniyor…", "Processing…"],
  ["Arka planı kaldır", "Remove background"],
  ["AI bağlantısını kontrol et", "Check AI connection"],
  ["Örnek sonucu göster", "Show sample result"],
  ["PNG indir", "Download PNG"],
  ["Örnek PNG indir", "Download sample PNG"],
  ["yerel dosya", "local file"],
  ["temsili şişe örneği", "sample bottle image"],
  ["Fotoğraf yüklemek üretim işlemi başlatmaz.", "Uploading a photo does not start a generation job."],
  ["Kalan hak:", "Uses remaining:"],
  ["İşlem düğmesine basıldığında fotoğraf mevcut API’ye gönderilir.", "Your photo is sent to the connected API only after you press the action button."],
  ["Demo, yalnızca hazır örneğin dekupe sonucunu içerir. Kendi fotoğrafın için mevcut AI API’sini bağlamak gerekir.", "The demo contains only the prepared sample cutout. Processing your own photo requires the connected AI API."],
  ["Gerçek fotoğrafla başla", "Start with a real photo"],
  ["Örnek yerine kendi ürün fotoğrafını da yükleyebilirsin.", "You can upload your own product photo instead of using the sample."],
  ["Sonucu karşılaştır", "Compare the result"],
  ["Kaydırıcıyla kenarları ve detayları incele.", "Use the slider to inspect edges and details."],
  ["PNG olarak indir", "Download as PNG"],
  ["Saydam veya seçtiğin düz zeminle dışa aktar.", "Export with transparency or your selected solid background."],
  ["İşlemler görünür", "Clear processing states"],
  ["Demo çıktısı ve gerçek API çıktısı ayrı etiketlenir.", "Demo output and real API output are labelled separately."],
  ["Yüklenen fotoğraf", "Uploaded photo"],
  ["Yerel önizleme", "Local preview"],
  ["Yüklediğiniz fotoğraf", "Your uploaded photo"],
  ["Henüz AI işlemi uygulanmadı.", "No AI processing has been applied yet."],
  ["Hazır örneğe dön", "Return to sample"],
  ["Onaylı şişe örneği", "Approved bottle sample"],
  ["Görünüm", "View"],
  ["Karşılaştır", "Compare"],
  ["Orijinal", "Original"],
  ["Sonuç", "Result"],
  ["Arka plan kaldırılmış sonuç", "Background-removed result"],
  ["Önceden hazırlanmış örnek dekupe", "Prepared sample cutout"],
  ["Hazır örnek çıktı", "Prepared sample output"],
  ["Önce ve sonra karşılaştırması", "Before and after comparison"],
  ["Ayrıntıları karşılaştır", "Compare details"],
  ["API tarafından döndürülen çıktı", "Output returned by the API"],
  ["Temsili şişe görseli · Hazır dekupe", "Sample bottle image · Prepared cutout"],
  ["SONRAKİ ADIM · ÜCRETSİZ + ÜYELİKLİ", "NEXT STEP · FREE + MEMBER ACCESS"],
  ["Kendi sahneni kur.", "Build your own scene."],
  ["Kendi arka planını yükle; ürününü sürükle, boyutlandır ve döndür. Manuel yerleştirme ücretsizdir; indirmek için üyelik gerekir. AI ile sahne üretimi ayrı ve kredilidir.", "Upload your own background, then drag, resize, and rotate your product. Manual placement is free; downloading requires membership. AI scene generation is separate and uses credits."],
  ["Sahneye yerleştir", "Place in scene"],
  ["Senin stilin.", "Your style."],
  ["Önce okunabilirlik.", "Readability first."],
  ["İçeriğini gir, hazır şeklini seç. QR yapısı korunur; her değişiklikte dijital veri kontrolü yeniden çalışır.", "Enter your content and choose a preset shape. The QR structure stays protected and the digital data check reruns after every change."],
  ["Ücretsiz · Kayıt yok", "Free · No signup"],
  ["Hazır vektörel şekiller", "Vector shape presets"],
  ["Kontrollü PNG + SVG", "Verified PNG + SVG"],
  ["İçeriğini seç", "Choose your content"],
  ["Hazır şeklini seç", "Choose a preset shape"],
  ["QR modül şekli", "QR module shape"],
  ["Şekil yalnız veri alanına uygulanır. İşaret köşe, hizalama, zamanlama ve bilgi alanları kare olarak korunur.", "The shape applies only to data modules. Finder, alignment, timing, and information areas remain square."],
  ["Renk ve çıktı boyutu", "Color and output size"],
  ["Koyu QR rengi", "Dark QR color"],
  ["Çıktı boyutu", "Output size"],
  ["Yapısal alanlar kilitli.", "Structural areas are locked."],
  ["Beyaz zemin, dört modüllük boş kenar ve H hata düzeltmesi korunur. Logo örtüşmesi, şeffaf zemin ve serbest çizim bu sürümde yok.", "The white background, four-module quiet zone, and H error correction are preserved. Logo overlays, transparent backgrounds, and freehand shapes are not available in this version."],
  ["QR önizlemesi", "QR preview"],
  ["Çıktı hazırlanıyor.", "Preparing output."],
  ["Kontrol bekleniyor", "Waiting for verification"],
  ["Geçerli içerik ve okunabilir bir çıktı hazırlanmalı.", "Valid content and a readable output are required."],
  ["SVG indir", "Download SVG"],
  ["Test geçmeden indirme açılmaz. Baskıdan önce son boyutta telefonla tara.", "Downloads remain disabled until verification passes. Scan at final print size with a phone before production."],
  ["Dijital kontrol neyi doğruluyor?", "What does the digital check verify?"],
  ["SVG görüntüsünün ve indirilecek PNG&apos;nin bilinen ızgarasından veri okunur; biçim, yönlendirme alanları, hata kontrolü ve içerik eşleşmesi sınanır. Nihai boyut, 6 piksel/modül ve hafif bulanıklıkta toplam 9 kontrol yapılır.", "Data is read from the known grid of the SVG and downloadable PNG. Format, finder areas, error correction, and payload matching are checked across 9 tests at final size, 6 pixels per module, and slight blur."],
  ["Bu işlem, kamerayla QR bulma testi veya her telefonda okuma garantisi değildir. Hazır stil örnekleri geliştirme testlerinde OpenCV ve ZBar ile ayrıca okunur. Üretim baskısını gerçek cihazda kontrol et.", "This is not a camera-detection test or a guarantee for every phone. Preset styles are also checked with OpenCV and ZBar during development. Test the production print on real devices."],
  ["QR içeriği", "QR content"],
  ["Okunabilirlik önce gelir", "Readability comes first"],
  ["Yapısal alanlar değişmez; hatalı sonuç indirmeye açılmaz.", "Structural areas stay intact and invalid output cannot be downloaded."],
  ["Gerçek vektörel çıktı", "True vector output"],
  ["Şekiller SVG yollarıdır; PNG aynı görüntüden üretilir.", "Shapes are SVG paths and the PNG is rendered from the same image."],
  ["AI kredisi harcamaz", "Uses no AI credits"],
  ["Hazır şekiller ve kontroller tarayıcıda çalışır.", "Preset shapes and checks run in your browser."],
  ["Son baskıyı test et", "Test the final print"],
  ["Malzeme, boyut ve telefon sonucu etkileyebilir.", "Material, size, and phone can affect the result."],
  ["Web adresi", "Web address"],
  ["https:// ile başlayan bağlantını gir.", "Enter a link beginning with https://."],
  ["Ad soyad *", "Full name *"],
  ["Adınız Soyadınız", "Your full name"],
  ["Telefon", "Phone"],
  ["E-posta", "Email"],
  ["Kurum / marka", "Organization / brand"],
  ["Marka adı", "Brand name"],
  ["Web sitesi", "Website"],
  ["Ağ adı (SSID) *", "Network name (SSID) *"],
  ["Misafir ağı", "Guest network"],
  ["Ağ şifresi", "Network password"],
  ["Paylaşılacak WiFi şifresi", "WiFi password to share"],
  ["Şifreleme", "Encryption"],
  ["Şifresiz ağ", "Open network"],
  ["QR, ağ şifresini içerir. Yalnızca paylaşmak istediğin bir misafir ağını kullan.", "The QR contains the network password. Use only a guest network you intend to share."],
  ["WiFi için özel WSC/NDEF kodlaması gerekir. Bu bağımsız sürümde WiFi yazımı kapalıdır; QR aracını kullanabilirsin.", "WiFi requires WSC/NDEF encoding. WiFi writing is disabled in this standalone version; use the QR tool instead."],
  ["Telefon numarası *", "Phone number *"],
  ["E-posta adresi *", "Email address *"],
  ["Konu", "Subject"],
  ["Merhaba", "Hello"],
  ["Mesaj", "Message"],
  ["Enlem *", "Latitude *"],
  ["Boylam *", "Longitude *"],
  ["Ondalık ayırıcı olarak nokta kullan.", "Use a period as the decimal separator."],
  ["Metin *", "Text *"],
  ["Android paket adı *", "Android package name *"],
  ["Google Play bağlantısı ve Android uygulama kaydı yazılır.", "Writes a Google Play link and Android application record."],
  ["Klasik", "Classic"],
  ["Tam kare", "Full square"],
  ["Yumuşak", "Rounded"],
  ["Yuvarlak köşe", "Soft corners"],
  ["Nokta", "Dots"],
  ["Dolu daire", "Filled circles"],
  ["Elmas", "Diamond"],
  ["Dolu baklava", "Filled diamonds"],
  ["Yıldız", "Star"],
  ["Kalın merkez", "Bold center"],
  ["SANATSAL QR", "ARTISTIC QR"],
  ["ÜCRETLİ ÖZEL TASARIM", "PAID CUSTOM DESIGN"],
  ["Sadece bir kod değil.", "More than a code."],
  ["Markanın bir parçası.", "Part of your brand."],
  ["Ambalajında, kartvizitinde ya da vitrinde. Bağlantını, markanın görsel dünyasıyla buluşturan bir tasarım yaklaşımı.", "For packaging, business cards, or displays. A design approach that connects your link with your brand's visual world."],
  ["Sanatsal QR’ı keşfet", "Explore artistic QR"],
  ["Standart QR ücretsiz", "Standard QR is free"],
  ["Ücretsiz QR aracından ayrı sunulur. Görselin taranabilirliği doğrulanmadı.", "Offered separately from the free QR tool. The sample image has not been verified for scanability."],
  ["Sanatsal QR özel tasarım örneğini incele", "View the artistic QR custom design sample"],
  ["Paylaştığınız altın, mor ve turkuaz çiçek desenli sanatsal QR örneği", "Artistic QR sample with gold, purple, and turquoise floral patterns"],
  ["ÇİÇEK & ORNAMENT", "FLORAL & ORNAMENT"],
  ["#ffffff arka plan", "#ffffff background"],
  ["#eee9e2 arka plan", "#eee9e2 background"],
  ["#e9e4f6 arka plan", "#e9e4f6 background"],
  ["#dce8df arka plan", "#dce8df background"],
  ["#202832 arka plan", "#202832 background"],
  ["Özel tasarım örneği", "Custom design sample"],
  ["Bir dokunuşla ", "Connect with "],
  ["bağlantı kur.", "one tap."],
  ["NFC etiketine web adresi veya iletişim bilgisi yaz. Önce içeriği hazırla, sonra uyumlu telefonla etikete aktar.", "Write a web address or contact details to an NFC tag. Prepare the content first, then transfer it with a compatible phone."],
  ["Uygulama kurmadan", "No app installation"],
  ["Uyumlu Android + Chrome", "Compatible Android + Chrome"],
  ["Fiziksel etiket gerekir", "Physical tag required"],
  ["İçerik türünü seç", "Choose content type"],
  ["İçeriğini hazırla", "Prepare your content"],
  ["Etiketteki mevcut içeriğin üzerine yazılmasına izin ver.", "Allow overwriting the tag's existing content."],
  ["Etikete yaz", "Write to tag"],
  ["Etiketi oku", "Read tag"],
  ["İçeriği kopyala", "Copy content"],
  ["Durdur", "Stop"],
  ["Tarayıcı Web NFC sunuyor. Gerçek donanım ve etiket uygunluğu işlem sırasında doğrulanır.", "This browser provides Web NFC. Hardware and tag compatibility are verified during the operation."],
  ["Bu tarayıcıda NFC yazma kullanılamıyor. İçeriği hazırlayabilirsin; yazmak için HTTPS üzerinden NFC destekli Android telefonda Chrome ile aç.", "NFC writing is unavailable in this browser. You can prepare the content here; to write it, open this HTTPS page in Chrome on an NFC-enabled Android phone."],
  ["Bu sürümde kalıcı kilitleme ve toplu yazım yoktur. WiFi/WSC yazımı için mevcut projedeki NDEF modülü kullanılmalıdır.", "This version does not provide permanent locking or bulk writing. WiFi/WSC writing requires the project's dedicated NDEF module."],
  ["Temsili Android önizlemesi", "Illustrative Android preview"],
  ["Dokun, bağlantı kur.", "Tap to connect."],
  ["İçeriğini hazırlamaya başla.", "Start preparing your content."],
  ["Temsili telefon önizlemesi", "Illustrative phone preview"],
  ["Renderhane etiket tasarım örneği", "Renderhane tag design sample"],
  ["Tarayıcı desteği var", "Browser support detected"],
  ["Önce cihaz uyumluluğu", "Check device compatibility"],
  ["Yazmak için etiketi telefona yaklaştır.", "Hold the tag near the phone to write."],
  ["NFC donanımı, Chrome ve HTTPS gerekir.", "NFC hardware, Chrome, and HTTPS are required."],
  ["Web NFC ve cihaz NFC donanımı gerekli. İşlem için izin istenir.", "Web NFC and device NFC hardware are required. The browser will ask for permission."],
  ["iPhone tarayıcısı", "iPhone browser"],
  ["Buradan etikete yazma sunulmaz. Etiket okuma cihaz ve içerikle değişir.", "Tag writing is not available here. Reading behavior depends on the device and content."],
  ["İçeriği açıkça gör", "Review content clearly"],
  ["Yazmadan önce bağlantıyı ve iletişim bilgilerini kontrol et.", "Check the link and contact details before writing."],
  ["İzin senin kontrolünde", "You control permission"],
  ["Üzerine yazma seçeneği varsayılan olarak kapalıdır.", "Overwrite is off by default."],
  ["Cihazı önce kontrol et", "Check the device first"],
  ["Tarayıcı desteği, fiziksel donanım garantisi değildir.", "Browser support does not guarantee compatible hardware."],
  ["Gerçek donanım bağlantısı", "Real hardware interaction"],
  ["Yazma başarı mesajı ancak cihaz onayından sonra gelir.", "A success message appears only after the device confirms the write."],
  ["QR içerik türü", "QR content type"],
  ["NFC içerik türü", "NFC content type"],
  ["Yeniden kontrol ediliyor", "Rechecking"],
  ["Girdi değişti. Önceki onay artık geçerli değil.", "The input changed. The previous verification is no longer valid."],
  ["Dijital veri kontrolü sürüyor", "Digital data check in progress"],
  ["SVG görüntüleniyor; QR verisi ve hata kontrolü sınanıyor.", "The SVG is visible while QR payload and error correction are checked."],
  ["Dijital veri kontrolü geçti", "Digital data check passed"],
  ["Klasik karşılaştırma da geçti", "Classic baseline also passed"],
  ["Klasik QR", "Classic QR"],
  ["kontrol · İçerik birebir eşleşti", "checks · Exact payload match"],
  ["İndirme kapalı", "Download disabled"],
  ["QR doğrulanamadı.", "QR verification failed."],
  ["Güncel çıktının kontrolleri tamamlanmadan indirme yapılamaz.", "You cannot download until the current output has passed verification."],
  ["WiFi QR kodu ağ adını ve şifresini içerir. Şifre bu önizlemede gizlendi.", "The WiFi QR code contains the network name and password. The password is hidden in this preview."],
  ["Hazır örnek çıktı gösteriliyor. Bu işlem AI çağrısı değildir.", "Showing the prepared sample output. This is not an AI request."],
  ["Fotoğraf önizleniyor. Gerçek işlem için removeBackground API adaptörünü bağla.", "The photo is being previewed. Connect the removeBackground API adapter for real processing."],
  ["İşlem tamamlandı. Sonucu kontrol ederek indir.", "Processing completed. Review the result before downloading."],
  ["İşlem başarısız oldu.", "Processing failed."],
  ["Fotoğraf yalnızca bu tarayıcıya yüklendi.", "The photo was loaded only in this browser."],
  ["Yalnızca JPG, PNG veya WebP yükleyin.", "Upload only JPG, PNG, or WebP files."],
  ["Dosya 5 MB sınırını aşıyor.", "The file exceeds the 5 MB limit."],
  ["Görsel çok büyük: en fazla 24 megapiksel.", "The image is too large: maximum 24 megapixels."],
  ["Dosya açılamadı.", "The file could not be opened."],
  ["Görsel açılamadı.", "The image could not be opened."],
  ["Görsel dışa aktarılamadı.", "The image could not be exported."],
  ["Çıktı indirilemedi. Sunucu CORS ve indirme izinlerini kontrol edin.", "The output could not be downloaded. Check the server's CORS and download permissions."],
  ["Canvas desteklenmiyor.", "Canvas is not supported."],
  ["İndirme başarısız.", "Download failed."],
  ["Web adresini girin.", "Enter a web address."],
  ["http:// veya https:// ile başlayan geçerli bir adres girin.", "Enter a valid address beginning with http:// or https://."],
  ["Yalnızca kimlik bilgisi içermeyen HTTP/HTTPS adresleri destekleniyor.", "Only HTTP/HTTPS addresses without embedded credentials are supported."],
  ["Telefon alanını doldurun.", "Complete the phone field."],
  ["Telefon numarasını ülke koduyla girin.", "Enter the phone number with its country code."],
  ["Ad soyad alanını doldurun.", "Complete the full name field."],
  ["Ağ adı alanını doldurun.", "Complete the network name field."],
  ["Geçersiz şifreleme seçeneği.", "Invalid encryption option."],
  ["WiFi şifresini girin.", "Enter the WiFi password."],
  ["E-posta alanını doldurun.", "Complete the email field."],
  ["Geçerli bir e-posta adresi girin.", "Enter a valid email address."],
  ["Enlem alanını doldurun.", "Complete the latitude field."],
  ["Boylam alanını doldurun.", "Complete the longitude field."],
  ["Enlem −90…90, boylam −180…180 aralığında olmalı.", "Latitude must be −90…90 and longitude −180…180."],
  ["Paket adı alanını doldurun.", "Complete the package name field."],
  ["Geçerli bir Android paket adı girin (ör. com.firma.uygulama).", "Enter a valid Android package name (for example com.company.app)."],
  ["Metin alanını doldurun.", "Complete the text field."],
  ["Bilinmeyen QR şekli.", "Unknown QR shape."],
  ["İçerik boş olamaz; en fazla 1200 UTF-8 bayt kullanın.", "Content cannot be empty; use at most 1200 UTF-8 bytes."],
  ["Çıktı boyutu 256–2048 piksel olmalı.", "Output size must be between 256 and 2048 pixels."],
  ["Daha koyu bir renk seçin. Bu sürümün renk kuralı beyaz zeminde en az 7:1 kontrasttır.", "Choose a darker color. This version requires at least 7:1 contrast on white."],
  ["NFC destekli Android, Chrome ve HTTPS gerekir.", "An NFC-enabled Android device, Chrome, and HTTPS are required."],
  ["WiFi/WSC yazımı bu sürümde kapalı.", "WiFi/WSC writing is disabled in this version."],
  ["İçeriği kontrol edin.", "Check the content."],
  ["Etiketi telefonun arkasına yaklaştır. Yazma tamamlanana kadar uzaklaştırma.", "Hold the tag near the back of the phone until writing finishes."],
  ["Okumak istediğin etiketi yaklaştır.", "Hold the tag you want to read near the phone."],
  ["20 saniye içinde etiket algılanmadı. İşlemi yeniden başlatabilirsin.", "No tag was detected within 20 seconds. You can start the operation again."],
  ["Etiket yazıldı. Kullanacağın cihazla okuyarak test et.", "Tag written. Read it with the intended device to test it."],
  ["Etiket okundu:", "Tag read:"],
  ["ikili veri", "binary data"],
  ["Etiket okunamadı. Biçim veya yakınlığı kontrol et.", "The tag could not be read. Check its format and distance."],
  ["Bilinmeyen hata", "Unknown error"],
  ["NFC izni verilmedi. İzinleri kontrol ederek tekrar dene.", "NFC permission was denied. Check permissions and try again."],
  ["Cihaz veya etiket bu işlemi desteklemiyor.", "The device or tag does not support this operation."],
  ["NFC işlemi tamamlanmadı:", "NFC operation did not complete:"],
  ["Panoya erişim için HTTPS veya localhost gerekir.", "Clipboard access requires HTTPS or localhost."],
  ["WiFi şifresini kopyalamak yerine QR aracını kullan.", "Use the QR tool instead of copying a WiFi password."],
  ["İçerik panoya kopyalandı.", "Content copied to the clipboard."],
  ["Kopyalama için HTTPS veya localhost gerekir.", "Copying requires HTTPS or localhost."],
  ["İşlem durduruldu.", "Operation stopped."],
  ["Bağlantı hazırlandı. Etikete henüz yazılmadı.", "The link is ready. It has not been written to a tag."],
  ["Bağlantı aktarıldı. Yeni QR kontrol ediliyor.", "Link applied. The new QR code is being verified."],
  ["Bağlantı aktarıldı. Yazma için ayrıca etiket ve onay gerekir.", "Link applied. Writing still requires a tag and confirmation."],
  ["Sayfa arka plana geçtiği için NFC işlemi durduruldu.", "The NFC operation stopped because the page moved to the background."],
];

const DYNAMIC: Array<[RegExp, string]> = [
  [/^([0-9]+) × ([0-9]+) px · ([0-9]+) × ([0-9]+) modül · H · 4 modül kenar$/, "$1 × $2 px · $3 × $4 modules · H · 4-module quiet zone"],
  [/^([0-9]+)[/]([0-9]+) kontrol · İçerik birebir eşleşti · Klasik QR$/, "$1/$2 checks · Exact payload match · Classic QR"],
  [/^([0-9]+)[/]([0-9]+) kontrol · İçerik birebir eşleşti · Klasik karşılaştırma da geçti$/, "$1/$2 checks · Exact payload match · Classic baseline also passed"],
];

export function localizeToolText(value: string): string {
  let result = value;
  for (const [source, target] of [...COPY].sort((a, b) => b[0].length - a[0].length)) result = result.replaceAll(source, target);
  for (const [pattern, replacement] of DYNAMIC) result = result.replace(pattern, replacement);
  return result;
}

export function localizeToolMarkup(markup: string): string {
  return localizeToolText(markup);
}

export function englishInspiration(channel: IdeaChannel): string {
  const isQr = channel === "qr";
  const title = isQr ? "Practical QR ideas" : "Practical NFC ideas";
  const description = isQr
    ? "Link to product guides, contact cards, menus, event pages, or support content. Keep the destination under your control and test the final print on real phones."
    : "Link tags to product guides, contact details, support pages, or digital experiences. Use short HTTPS links and test the finished tag on its final material.";
  return '<section class="rh-ideas" id="rh-inspiration" aria-labelledby="rh-ideas-title"><header class="rh-ideas-header"><div><div class="rh-idea-eyebrow"><span></span> IDEAS & USE CASES</div><h2 id="rh-ideas-title">' + title + '</h2><p>' + description + '</p></div></header><div class="rh-idea-intro"><strong>Keep it dependable</strong><span>The code or tag stores access information; it does not host the destination, prove ownership, or guarantee compatibility. Test the complete experience before publishing or production.</span></div></section>';
}
