import type { Metadata } from "next";
import Script from "next/script";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "@/app/globals.css";

const GA_ID = "G-PLZ6ZW54KV";

// Validates all required env vars at startup — fails fast if any are missing
import "@/lib/env";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const BASE_URL = "https://renderhane.com";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "common" });
  const title = `Renderhane — ${t("tagline")}`;
  const description =
    locale === "tr"
      ? "Tek fotoğraftan profesyonel ürün görseli, 3D model ve video üretin. Yapay zeka destekli e-ticaret stüdyosu."
      : "Generate professional product visuals, 3D models and videos from a single photo. AI-powered e-commerce studio.";

  return {
    title,
    description,
    metadataBase: new URL(BASE_URL),
    alternates: {
      canonical: `/${locale}`,
      languages: { tr: "/tr", en: "/en" },
    },
    openGraph: {
      title,
      description,
      url: `${BASE_URL}/${locale}`,
      siteName: "Renderhane",
      locale: locale === "tr" ? "tr_TR" : "en_US",
      type: "website",
      // OG image is auto-generated by src/app/opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // Twitter image inherits from opengraph-image.tsx
    },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true },
    },
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        name: "Renderhane",
        url: BASE_URL,
        logo: `${BASE_URL}/icon.png`,
        description:
          locale === "tr"
            ? "Yapay zeka destekli e-ticaret ürün görseli üretim platformu"
            : "AI-powered e-commerce product visual generation platform",
      },
      {
        "@type": "WebApplication",
        name: "Renderhane",
        url: BASE_URL,
        applicationCategory: "DesignApplication",
        operatingSystem: "Web",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "TRY",
          description: locale === "tr" ? "20 ücretsiz kredi ile başla" : "Start with 20 free credits",
        },
      },
    ],
  };

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_ID}');
          `}
        </Script>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
